[2024-10-19T14:40:34.852+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T14:40:34.966+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tecnica_postgres.Leer_Data manual__2024-10-19T14:37:05.589850+00:00 [queued]>
[2024-10-19T14:40:35.033+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tecnica_postgres.Leer_Data manual__2024-10-19T14:37:05.589850+00:00 [queued]>
[2024-10-19T14:40:35.039+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T14:40:35.174+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresFileOperator): Leer_Data> on 2024-10-19 14:37:05.589850+00:00
[2024-10-19T14:40:35.307+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Leer_Data', 'manual__2024-10-19T14:37:05.589850+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_postgres.py', '--cfg-path', '/tmp/tmp52nlt8n9']
[2024-10-19T14:40:36.038+0000] {standard_task_runner.py:105} INFO - Job 154: Subtask Leer_Data
[2024-10-19T14:40:35.316+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=257) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T14:40:36.432+0000] {standard_task_runner.py:72} INFO - Started process 259 to run task
[2024-10-19T14:40:37.424+0000] {task_command.py:467} INFO - Running <TaskInstance: tecnica_postgres.Leer_Data manual__2024-10-19T14:37:05.589850+00:00 [running]> on host 953088fb6bc9
[2024-10-19T14:40:37.774+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tecnica_postgres' AIRFLOW_CTX_TASK_ID='Leer_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T14:37:05.589850+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T14:37:05.589850+00:00'
[2024-10-19T14:40:37.777+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-19T14:40:37.778+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-19T14:40:37.780+0000] {logging_mixin.py:190} INFO - Current task name:Leer_Data state:running start_date:2024-10-19 14:40:34.970647+00:00
[2024-10-19T14:40:37.781+0000] {logging_mixin.py:190} INFO - Dag name:tecnica_postgres and current dag run status:running
[2024-10-19T14:40:37.782+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T14:40:37.812+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-10-19T14:40:37.916+0000] {logging_mixin.py:190} INFO - [('MLA929616779', 'MLA', 'MicroondasGrillBghQuickChefB228db9Blanco28l220v', '334999', '50', 'http://http2.mlstatic.com/D_815777-MLU72650817795_112023-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA1450975507', 'MLA', 'MicroondasDigitalConGrillAtma28l900wTdgb28cnpiNegro', '315990', '50', 'http://http2.mlstatic.com/D_883827-MLU77494890379_072024-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA1116129043', 'MLA', 'MicroondasDigitalDaewoo20Litros700wD120d200w', '212126.03', '50', 'http://http2.mlstatic.com/D_600222-MLU79065109317_092024-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA1371468617', 'MLA', 'HornoMicroondasDigitalGrillRenacer23lts800wCr823mg', '271699', '50', 'http://http2.mlstatic.com/D_772171-MLA47425763143_092021-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA1876627538', 'MLA', 'MicroondasRotativoMatrb20an20lts700wNegroAtma', '214999', '50', 'http://http2.mlstatic.com/D_859748-MLU73266638951_122023-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA922685043', 'MLA', 'MicroondasBgh28Litros220vDigitalEcoB228ds20', '348999', '150', 'http://http2.mlstatic.com/D_685390-MLU72491323848_102023-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA854741215', 'MLA', 'MicroondasBghQuickChefB120db9Blanco20l220v', '246999.05', '50', 'http://http2.mlstatic.com/D_739532-MLU72581100810_112023-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA1931245042', 'MLA', 'MicroondasMec치nicoRenacer20LitrosColorBlanco700w5Niveles', '222998', '150', 'http://http2.mlstatic.com/D_704816-MLA79581695670_102024-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA1929759836', 'MLA', 'MicroondasKanjihomeKjh-mw2xlx00123LtsDigital', '227998', '200', 'http://http2.mlstatic.com/D_600632-MLA79519374329_092024-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA910524436', 'MLA', 'MicroondasDigitalBghQuickChefB330dss9Trifunci칩n30L', '502319.08', '50', 'http://http2.mlstatic.com/D_949071-MLU72338775643_102023-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA1386452985', 'MLA', 'MicroondasRotativoMpr8620nPhilcoBlanco20Litros700w', '199999', '250', 'http://http2.mlstatic.com/D_731608-MLU74992703486_032024-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA1928169418', 'MLA', 'HornoMicroondasManualCr20LitrosCr720700w5Niveles', '185998', '150', 'http://http2.mlstatic.com/D_646631-MLA52041395911_102022-I.jpg', '2024-10-19 14:31:32.306112'), ('MLA929616779', 'MLA', 'MicroondasGrillBghQuickChefB228db9Blanco28l220v', '334999', '50', 'http://http2.mlstatic.com/D_815777-MLU72650817795_112023-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA1450975507', 'MLA', 'MicroondasDigitalConGrillAtma28l900wTdgb28cnpiNegro', '315990', '50', 'http://http2.mlstatic.com/D_883827-MLU77494890379_072024-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA1116129043', 'MLA', 'MicroondasDigitalDaewoo20Litros700wD120d200w', '212126.03', '50', 'http://http2.mlstatic.com/D_600222-MLU79065109317_092024-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA1371468617', 'MLA', 'HornoMicroondasDigitalGrillRenacer23lts800wCr823mg', '271699', '50', 'http://http2.mlstatic.com/D_772171-MLA47425763143_092021-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA1876627538', 'MLA', 'MicroondasRotativoMatrb20an20lts700wNegroAtma', '214999', '50', 'http://http2.mlstatic.com/D_859748-MLU73266638951_122023-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA922685043', 'MLA', 'MicroondasBgh28Litros220vDigitalEcoB228ds20', '348999', '150', 'http://http2.mlstatic.com/D_685390-MLU72491323848_102023-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA854741215', 'MLA', 'MicroondasBghQuickChefB120db9Blanco20l220v', '246999.05', '50', 'http://http2.mlstatic.com/D_739532-MLU72581100810_112023-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA1931245042', 'MLA', 'MicroondasMec치nicoRenacer20LitrosColorBlanco700w5Niveles', '222998', '150', 'http://http2.mlstatic.com/D_704816-MLA79581695670_102024-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA1929759836', 'MLA', 'MicroondasKanjihomeKjh-mw2xlx00123LtsDigital', '227998', '200', 'http://http2.mlstatic.com/D_600632-MLA79519374329_092024-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA910524436', 'MLA', 'MicroondasDigitalBghQuickChefB330dss9Trifunci칩n30L', '502319.08', '50', 'http://http2.mlstatic.com/D_949071-MLU72338775643_102023-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA1386452985', 'MLA', 'MicroondasRotativoMpr8620nPhilcoBlanco20Litros700w', '199999', '250', 'http://http2.mlstatic.com/D_731608-MLU74992703486_032024-I.jpg', '2024-10-19 14:40:06.743691'), ('MLA1928169418', 'MLA', 'HornoMicroondasManualCr20LitrosCr720700w5Niveles', '185998', '150', 'http://http2.mlstatic.com/D_646631-MLA52041395911_102022-I.jpg', '2024-10-19 14:40:06.743691')]
[2024-10-19T14:40:39.449+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/PostgresFileOperator.py", line 29, in execute
    self.readTable()
  File "/opt/airflow/dags/PostgresFileOperator.py", line 60, in readTable
    smtp.login(email_sender, email_password)
  File "/usr/local/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/local/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 00721157ae682-6e5c010b602sm7581927b3.60 - gsmtp')
[2024-10-19T14:40:39.941+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-19T14:40:39.943+0000] {logging_mixin.py:190} INFO - Task start:2024-10-19 14:40:34.970647+00:00 end:2024-10-19 14:40:39.923185+00:00 duration:4.952538
[2024-10-19T14:40:39.945+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresFileOperator): Leer_Data> dag:<DAG: tecnica_postgres> dagrun:<DagRun tecnica_postgres @ 2024-10-19 14:37:05.589850+00:00: manual__2024-10-19T14:37:05.589850+00:00, state:running, queued_at: 2024-10-19 14:37:05.940990+00:00. externally triggered: True>
[2024-10-19T14:40:39.949+0000] {logging_mixin.py:190} INFO - Failure caused by (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 00721157ae682-6e5c010b602sm7581927b3.60 - gsmtp')
[2024-10-19T14:40:39.951+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tecnica_postgres, task_id=Leer_Data, run_id=manual__2024-10-19T14:37:05.589850+00:00, execution_date=20241019T143705, start_date=20241019T144034, end_date=20241019T144039
[2024-10-19T14:40:40.102+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T14:40:40.105+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 154 for task Leer_Data ((534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 00721157ae682-6e5c010b602sm7581927b3.60 - gsmtp'); 259)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/PostgresFileOperator.py", line 29, in execute
    self.readTable()
  File "/opt/airflow/dags/PostgresFileOperator.py", line 60, in readTable
    smtp.login(email_sender, email_password)
  File "/usr/local/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/local/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 00721157ae682-6e5c010b602sm7581927b3.60 - gsmtp')
[2024-10-19T14:40:40.277+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-19T14:40:40.443+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-19T14:40:40.448+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
