[2024-10-19T12:50:03.447+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T12:50:03.464+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tecnica_postgres.Insertar_Data manual__2024-10-19T12:49:52.608286+00:00 [queued]>
[2024-10-19T12:50:03.474+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tecnica_postgres.Insertar_Data manual__2024-10-19T12:49:52.608286+00:00 [queued]>
[2024-10-19T12:50:03.475+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T12:50:03.490+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresFileOperator): Insertar_Data> on 2024-10-19 12:49:52.608286+00:00
[2024-10-19T12:50:03.497+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T12:50:03.499+0000] {standard_task_runner.py:72} INFO - Started process 185 to run task
[2024-10-19T12:50:03.498+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Insertar_Data', 'manual__2024-10-19T12:49:52.608286+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_postgres.py', '--cfg-path', '/tmp/tmp8b3u0t9a']
[2024-10-19T12:50:03.500+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask Insertar_Data
[2024-10-19T12:50:03.545+0000] {task_command.py:467} INFO - Running <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-10-19T12:49:52.608286+00:00 [running]> on host 6aed6f1a07ad
[2024-10-19T12:50:03.616+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tecnica_postgres' AIRFLOW_CTX_TASK_ID='Insertar_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T12:49:52.608286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T12:49:52.608286+00:00'
[2024-10-19T12:50:03.618+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-19T12:50:03.619+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-19T12:50:03.619+0000] {logging_mixin.py:190} INFO - Current task name:Insertar_Data state:running start_date:2024-10-19 12:50:03.465645+00:00
[2024-10-19T12:50:03.620+0000] {logging_mixin.py:190} INFO - Dag name:tecnica_postgres and current dag run status:running
[2024-10-19T12:50:03.621+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T12:50:03.621+0000] {postgres.py:191} INFO - Running copy expert: COPY productos_mercadolibre FROM STDIN, filename: C:/Users/Asus/Documents/Entrevista Data Engineer/Prueba_tecnica/***-docker/dags/tmp/file.tsv
[2024-10-19T12:50:03.622+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/PostgresFileOperator.py", line 20, in execute
    self.writeInTable()
  File "/opt/airflow/dags/PostgresFileOperator.py", line 27, in writeInTable
    self.postgres_hook.bulk_load(self.config.get('table_name'), 'C:/Users/Asus/Documents/Entrevista Data Engineer/Prueba_tecnica/airflow-docker/dags/tmp/file.tsv')
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 211, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 193, in copy_expert
    with open(filename, "w"):
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Asus/Documents/Entrevista Data Engineer/Prueba_tecnica/airflow-docker/dags/tmp/file.tsv'
[2024-10-19T12:50:03.632+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-19T12:50:03.633+0000] {logging_mixin.py:190} INFO - Task start:2024-10-19 12:50:03.465645+00:00 end:2024-10-19 12:50:03.632594+00:00 duration:0.166949
[2024-10-19T12:50:03.633+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresFileOperator): Insertar_Data> dag:<DAG: tecnica_postgres> dagrun:<DagRun tecnica_postgres @ 2024-10-19 12:49:52.608286+00:00: manual__2024-10-19T12:49:52.608286+00:00, state:running, queued_at: 2024-10-19 12:49:52.927131+00:00. externally triggered: True>
[2024-10-19T12:50:03.634+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'C:/Users/Asus/Documents/Entrevista Data Engineer/Prueba_tecnica/***-docker/dags/tmp/file.tsv'
[2024-10-19T12:50:03.634+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tecnica_postgres, task_id=Insertar_Data, run_id=manual__2024-10-19T12:49:52.608286+00:00, execution_date=20241019T124952, start_date=20241019T125003, end_date=20241019T125003
[2024-10-19T12:50:03.647+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T12:50:03.648+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 107 for task Insertar_Data ([Errno 2] No such file or directory: 'C:/Users/Asus/Documents/Entrevista Data Engineer/Prueba_tecnica/airflow-docker/dags/tmp/file.tsv'; 185)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/PostgresFileOperator.py", line 20, in execute
    self.writeInTable()
  File "/opt/airflow/dags/PostgresFileOperator.py", line 27, in writeInTable
    self.postgres_hook.bulk_load(self.config.get('table_name'), 'C:/Users/Asus/Documents/Entrevista Data Engineer/Prueba_tecnica/airflow-docker/dags/tmp/file.tsv')
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 211, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 193, in copy_expert
    with open(filename, "w"):
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Asus/Documents/Entrevista Data Engineer/Prueba_tecnica/airflow-docker/dags/tmp/file.tsv'
[2024-10-19T12:50:03.675+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-19T12:50:03.690+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-19T12:50:03.693+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
